name: Build SidebarLib

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      # Просто собираем без всяких API
      - name: Build with Maven
        run: mvn clean install
      
      # Сохраняем все JAR-файлы
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: sidebar-libs
          path: |
            **/target/*.jar
            !**/target/original-*.jar
            !**/target/*-sources.jar
